os: linux
arch: arm64-graviton2
group: edge
language: ruby
cache: bundler
gemfile: Gemfile
branches:
  only:
  - master
rvm:
- 2.6

script:
- gem install gem-release
- gem bump patch --file version.rb -m "bump made-slowly gem [skip travis]"
- git push https://$travis_public_repo_token@github.com/madeslowly/made-slowly.git
  HEAD:master
- gem build made-slowly.gemspec
deploy:
  provider: rubygems
  api:
    key:
      secure: UYrybjxVPxWkcCtb3mragNO81k7/liyZ6dLKkRVE3pb0WIS33HeRpnxoStU3GEl/qkZ9abqZ65zc+W8gT5hPBruRrVv2DDEXZOZUr1EVSZ/Gu+pyIJwNmS/oOp+8wswwr73gBRYcdr4l2X9K8KVlcilb67n9vh7IoGkWeGEDcMs2U2ldpswOPCd2NXMGaNGR6p9B0B8VXzaKjPHLXEUYwjPB9WWESSFpCJuXYPpttq6LN4fax+jNXeFY22bM7Ux3CGCA529Cz1D7BRF5vM/CjjhiXxDasxWuX+WQhYFJzV2DXz5WFpsk8N4//tjreKvZED7Ur39jTIuprbKnIc+0+E4Ctt4zhPk6L1gAiBEU4PBP5MjYnUFkgfyBJin6WMzSY1hsbXxlRXqp4OggOei2Up7y2Wvxq2GoDfAVkGdAOeEGIcJqx9chn/9LO7k9iPBVMz/otzETHuJWrMBcxMxdsN/mKHVcmCp4oocrMQZB8WuKHYauII4So4bm/nOCaEEbh5E1bNLStEBSXZlKtyHs0Ubgoc91ZKj0DxQKFGaw/6wi4rB1da/bVS0fUNRBWXxXEPZOH13FNDbFecBiK1Mj8ffW4M2D3zYpYSh6nzznIjrgwWBiTI37XwStmsSGXIknbcHht1yU7utYywK0IE19k/nkuDZFKPB08Q0cmzfjGE4=
